### PR TITLE
Support for Python 2.7

### PR DESCRIPTION
**Pull request by leighsmith**
- Some forwards compatible changes to allow rpp to continue to run on Python 2.7 (sadly a requirement for me ATM).

### CODE REVIEW

**Comment by Perlence** [comment]
That's a lot of commits! Looks like we were trying to fix the same things independently. Does the 0.3 version work for you (apart from the Python 2.7 backport)?

**Comment by Perlence** [comment]
> That's a lot of commits!
Do you mind squashing them to 2, e.g. "

**Comment by Perlence** [comment]
Sorry, my finger slipped.

**Comment by leighsmith** [comment]
v0.3 does work for me on Python v3, although extra work I had done to decode base64 DSP parameters remains to be ported to the new version. That's about the only reason I'm a bit reluctant to squash commits.

**Comment by Perlence** [comment]
Do you mind if I squash them myself?

**Comment by leighsmith** [comment]
That's fine by me, I can use my fork as the reference for porting further changes.

**Comment by Perlence** [comment]
Thanks @leighsmith and @shidephen! It would also be a pleasure to have that DSP handling as well!

**Pull request closed without merging**
